package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/thisjustinf/togo-list/internal/graphql/generated"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
