type Todo {
  id: ID!
  title: String!
  description: String!
  completed: Boolean!
  user: UUID!
  createdAt: Time!
  lastUpdatedAt: Time!
}

input CreateTodoDTO {
  title: String!
  description: String!
}

input UpdateTodoDTO {
  title: String
  description: String
  completed: String
}

extend type Query {
  getTodos(user: UUID!): [Todo!]
  getTodo(id: UUID!): Todo!
}

extend type Mutation {
  createTodo(createTodoDTO: CreateTodoDTO): UUID!
  updateTodo(updateTodoDTO: UpdateTodoDTO): Todo!
  deleteTodo(id: ID!): Boolean
}
